# Mathematical Operations by Numpy

In [2]:
import numpy as np

In [3]:
ar1 = np.arange(1,10).reshape(3,3)
print(ar1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
ar2 = np.arange(1,10).reshape(3,3)
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
ar1 + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# add() method

In [6]:
np.add(ar1 , ar2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
ar1 * ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# divide()

In [8]:
np.divide(ar1 , ar2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.multiply(ar1 , ar2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# matrix dot product by dot() method

In [10]:
ar1 @ ar2 

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [11]:
ar1.dot(ar2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [12]:
ar1.max()

9

In [13]:
ar1.argmax()

8

In [14]:
ar1.min()

1

# sum of all element in matrix

In [15]:
np.sum(ar1)

45

In [16]:
np.sum(ar1, axis = 0)

array([12, 15, 18])

In [17]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.sum(ar1, axis = 1)

array([ 6, 15, 24])

# mean of all elemtnt of matrix

In [19]:
ar1.mean()

5.0