In [2]:
import numpy as np
import random

# random() print random value 

In [3]:
random.random()

0.16368691516763556

random function of numpy(print array type value)

In [8]:
np.random.random(1)

array([0.87358546])

printing in multidimension arrays

In [10]:
np.random.random((2,2))

array([[0.40225284, 0.60626839],
       [0.76194898, 0.93463283]])

In [13]:
np.random.random((1,10))

array([[0.93581068, 0.40629394, 0.41157882, 0.17558757, 0.75850185,
        0.17675862, 0.39101809, 0.52162938, 0.35174801, 0.3829121 ]])

printing Integer type values here

In [14]:
np.random.randint(1,4)

2

In [22]:
np.random.randint(1,20,(3,4,3))

array([[[16,  1, 19],
        [ 8,  7,  2],
        [13,  7,  9],
        [18, 14,  7]],

       [[ 4,  6,  9],
        [ 4, 10,  6],
        [17, 17,  3],
        [12,  6,  3]],

       [[13, 15, 12],
        [14, 15,  4],
        [ 2,  3, 16],
        [11, 15, 14]]])

# rand()= it will print value under 0 to 1

In [7]:
np.random.rand(3,3)

array([[0.08857771, 0.99728658, 0.28028036],
       [0.45420833, 0.76875926, 0.57120134],
       [0.42873454, 0.95512114, 0.58329701]])

# randn() =it will print +ive and -ive values under 0 to 1

In [9]:
np.random.randn(3,3)

array([[-1.82170109, -1.11159883, -1.22330456],
       [ 0.50731979,  0.93006972,  2.07623649],
       [ 0.49817702, -0.11795576, -1.04880614]])

# choice() = it will print according to IDE choice in given sequence 

In [10]:
x = [1,2,3,4]
np.random.choice(x)

1

In [11]:
np.random.choice(x)

2

In [12]:
np.random.choice(x)

4

In [13]:
np.random.choice(x)

3

In [14]:
np.random.choice(x)

4

In [15]:
np.random.choice(x)

2