# Importing numpy

In [1]:
import numpy as np

# empty function

In [2]:
z = np.empty((3,4), dtype = str)
print(z)
z.dtype

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


dtype('<U1')

# ones()

In [3]:
z = np.ones((3,4), dtype = str) 
print(z)
z.dtype

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


dtype('<U1')

# arange()

In [4]:
# np.arange(start,end,steps)
arr = np.arange(1,19)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [5]:
odd_arr = np.arange(1,19,2)
print(odd_arr)

[ 1  3  5  7  9 11 13 15 17]


In [6]:
even_arr = np.arange(2,19,2)
print(even_arr)

[ 2  4  6  8 10 12 14 16 18]


# linspace()

In [7]:
np.linspace(1,10,2)

array([ 1., 10.])


# reshape() = for converting 1d to 2d,3d,4d

In [8]:
arr_3d = arr.reshape(3,6)
print(arr_3d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [9]:
arr_2d = arr.reshape(2,9)
print(arr_2d)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]



# ravel() = for converting 2d,3d to 1d

In [10]:
ar_1d = arr.ravel()
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


# flatten()

In [11]:
fltn = arr.flatten()
print(fltn)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


# tranpose() or T = for transposing the matrix

In [14]:
arr_2d.transpose()

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14],
       [ 6, 15],
       [ 7, 16],
       [ 8, 17],
       [ 9, 18]])

In [16]:
arr_3d.T

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])